# Funktion för att normalisera län och county-namn
def normalize_lan(lan):
    # Mappning för att korrigera länsnamn, både svenska och engelska
    lan_map = {
        "Västra Götaland län": "Västra Götalands län",
        "Västra Götalands län": "Västra Götalands län",
        "Västra Götaland County": "Västra Götalands län",
        "Skåne län": "Skåne län",
        "Skåne County": "Skåne län",
        "Västerbottens län": "Västerbottens län",
        "Västerbotten län": "Västerbottens län",
        "Västerbotten County": "Västerbottens län",
        "Stockholm län": "Stockholms län",
        "Stockholms län": "Stockholms län",
        "Stockholm County": "Stockholms län",
        "Norrbottens län": "Norrbottens län",
        "Norrbotten län": "Norrbottens län",
        "Norrbotten County": "Norrbottens län",
        "Västernorrlands län": "Västernorrlands län",
        "Västernorrland län": "Västernorrlands län",
        "Västernorrland County": "Västernorrlands län",
        "Västmanlands län": "Västmanlands län",
        "Västmanland län": "Västmanlands län",
        "Västmanland County": "Västmanlands län",
        "Gävleborgs län": "Gävleborgs län",
        "Gavleborg län": "Gävleborgs län",
        "Gavleborg County": "Gävleborgs län",
        "Jämtlands län": "Jämtlands län",
        "Jamtland län": "Jämtlands län",
        "Jamtland County": "Jämtlands län",
        "Dalarnas län": "Dalarnas län",
        "Dalarna län": "Dalarnas län",
        "Dalarna County": "Dalarnas län",
        "Jönköpings län": "Jönköpings län",
        "Jonkoping län": "Jönköpings län",
        "Jonkoping County": "Jönköpings län",
        "Södermanlands län": "Södermanlands län",
        "Södermanland län": "Södermanlands län",
        "Södermanland County": "Södermanlands län",
        "Uppsala län": "Uppsala län",
        "Hallands län": "Hallands län",
        "Halland län": "Hallands län",
        "Halland County": "Hallands län",
        "Kronobergs län": "Kronobergs län",
        "Kronoberg län": "Kronobergs län",
        "Kronoberg County": "Kronobergs län",
        "Blekinge län": "Blekinge län",
        "Blekinge County": "Blekinge län",
        "Östergötlands län": "Östergötlands län",
        "Östergötland län": "Östergötlands län",
        "Östergötland County": "Östergötlands län",
        "Örebro län": "Örebro län",
        "Örebro County": "Örebro län",
        "Värmlands län": "Värmlands län",
        "Varmland län": "Värmlands län",
        "Varmland County": "Värmlands län",
        "Gotlands län": "Gotlands län",
        "Gotland län": "Gotlands län",
        "Gotland County": "Gotlands län",
        "Ingen län hittad": "Ingen län hittad",
        "Kalmar County": "Kalmar län",
        "Okänd län": "Okänd län"
    }

    return lan_map.get(lan, lan)