Table fct_traffic_situation {
  id INTEGER [primary key]
  time_key INTEGER [ref: >dim_time.time_id]
  location_key INTEGER [ref: >dim_location.location_id]
  message_key INTEGER [ref: >dim_message.message_id]
  icon_id STRING
  affected_direction STRING
  number_of_lanes_restricted INTEGER
  temporary_limit INTEGER
  location_descriptor STRING
  traffic_restriction_type STRING
}

Table dim_time {
  time_id INTEGER [primary key]
  start_time DATETIME [not null]
  end_time DATETIME
  creation_time DATETIME
  start_year INTEGER [not null]
  start_month INTEGER [not null]
  start_day INTEGER [not null]
  start_hour INTEGER [not null]
  start_minute INTEGER [not null]
  start_second INTEGER [not null]
  end_year INTEGER
  end_month INTEGER
  end_day INTEGER
  end_hour INTEGER
  end_minute INTEGER
  end_second INTEGER
  creation_year INTEGER
  creation_month INTEGER
  creation_day INTEGER
  creation_hour INTEGER
  creation_minute INTEGER
  creation_second INTEGER
}

Table dim_location {
  location_id INTEGER [primary key]
  road_number_numeric INTEGER [not null]
  road_name STRING
  geometry_point_sweref99_tm STRING
  geometry_point_wgs84 STRING
  geometry_line_sweref99_tm STRING
  geometry_line_wgs84 STRING
}

Table dim_message {
  message_id INTEGER [primary key]
  message_type STRING [not null]
  message STRING [not null]
  severity_text STRING
  safety_related_message BOOLEAN
  message_code INTEGER
}